pull_request_rules:
  - name: Automatic squash merge when approved
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "-title~=(?i)WIP"
      - "base=gh-pages"
    actions:
      merge:
        strict: "smart"
        method: squash
        commit_message: "title+body"
  - name: Delete head branch after merge
    conditions:
      - "merged"
    actions:
      delete_head_branch: {}
  - name: Add label `Area-Content`
    conditions:
      - "files=index.md"
    actions:
      label:
        add: ["Area-Content"]
  - name: Request a review from the owner because it is a complex PR
    conditions:
      - 'title~=(?i)\[MEGA\]'
    actions:
      request_reviews:
        users: ["TieBaMma"]
